# Generated by Django 6.0.1 on 2026-01-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
