# Generated by Django 6.0.1 on 2026-01-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issuer', models.CharField(max_length=150)),
                ('date_awarded', models.DateField()),
                ('certificate_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
