# Generated by Django 6.0.1 on 2026-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
